name: flutter_smzg
description: 小密总管
# 版本号(编码规则：1位大版本，3位中版本，3位小版本，中间没有0)
# 打包编号(编码规则：1位大版本，3位中版本，3位小版本，跟BUILD_NAME对应，不足3位则补0)
version: 2.2.1+6
environment:
  sdk: ">=2.4.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_fordova:
  #   git: https://github.com/jiangyubao/fordova.git
  # flutter_common:
  #    git: https://github.com/jiangyubao/flutter_common.git
  dash_chat: 
    git: https://github.com/jiangyubao/dash_chat.git
  pointycastle:
    git: https://github.com/bcgit/pc-dart.git
  flutter_fordova:
    path: ../flutter_fordova
  flutter_common:
     path: ../flutter_common
  flutter_umpush:
      path: ../flutter_umpush
  flutter_wechat_plugin:
      path: ../flutter_wechat_plugin
  flutter_hyble: 
      path: ../flutter_hyble
  flutter_scc: 
      path: ../flutter_scc
  cupertino_icons: ^0.1.3
  flutter_progress_hud: 1.0.2
  keyboard_actions: 3.2.1+1
  image_picker: ^0.6.3+4
  pie_chart: 3.1.1
  font_awesome_flutter: 8.8.0
  get_it: 4.0.0
  qr_flutter: 3.2.0
  qr: ^1.2.0
  flutter_svprogresshud:
     git: https://github.com/flutter-beijing/flutter_svprogresshud.git
  date_format: 1.0.8
  flutter_linkify: 3.1.0
  pull_to_refresh: ^1.5.8
  fluro: ^1.5.1
  image_save: 1.1.1
  sqflite: ^1.3.1
  keyboard_visibility: 0.5.6
  permission_handler: 4.4.0
  share_extend: ^1.1.3
  markdown: 2.1.3
  flutter_screenutil: ^1.0.2
flutter_native_splash:
  iosImage: "assets/images/splash.png"
  androidImage: "android_images/splash.png"
  color: "FFFFFF"
dev_dependencies:
  flutter_launcher_icons: "^0.7.4"
  flutter_native_splash: 
    path: ../flutter_native_splash
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1024.png"
  image_path_android: "android_images/logo1024.png"
flutter:
  uses-material-design: true
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: SmzgIconFont
      fonts:
        - asset: assets/fonts/smzg_iconfont.ttf
  assets:
    - assets/images/
    - assets/doc/
flutter_intl:
  enabled: true
